### ISSUE TITLE
Problem when deploying LinkedGeoData

### ISSUE THREAD

**Issue by D063520** [GeoKnow/LinkedGeoData#27]
Hi,

I'm trying to follow the example in the README file. I get thorough until I do:

 sparqlify-tool -P lgd-example ontology

... I get the following error:

2017-12-23 23:09:00,746 WARN  org.aksw.sparqlify.core.cast.TypeSystemImpl: Skipping: geography, geography
2017-12-23 23:09:00,746 WARN  org.aksw.sparqlify.core.cast.TypeSystemImpl: Skipping: geometry, geometry
2017-12-23 23:09:00,746 WARN  org.aksw.sparqlify.core.cast.TypeSystemImpl: Skipping: timestamp, timestamp
2017-12-23 23:09:01,145 INFO  org.aksw.sparqlify.web.Main: Database product: PostgreSQL
2017-12-23 23:09:01,169 INFO  org.aksw.sparqlify.config.v0_2.bridge.SchemaProvider: Retrieving schema for query: SELECT * FROM "users"
2017-12-23 23:09:01,169 WARN  org.aksw.sparqlify.config.v0_2.bridge.SchemaProvider: Using ugly hack for adding a limit
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: relation "users" does not exist
  Position: 15
	at org.aksw.sparqlify.config.v0_2.bridge.SchemaProviderImpl.createSchemaForQueryString(SchemaProviderImpl.java:84)
	at org.aksw.sparqlify.config.v0_2.bridge.SchemaProviderImpl.createSchemaForRelationName(SchemaProviderImpl.java:58)
	at org.aksw.sparqlify.config.v0_2.bridge.SyntaxBridge.create(SyntaxBridge.java:228)
	at org.aksw.sparqlify.config.v0_2.bridge.ConfiguratorCandidateSelector.configure(ConfiguratorCandidateSelector.java:24)
	at org.aksw.sparqlify.web.Main.main(Main.java:232)
Caused by: java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: relation "users" does not exist
  Position: 15
	at org.aksw.sparqlify.config.v0_2.bridge.BasicTableProviderJdbc.getBasicTableInfo(BasicTableProviderJdbc.java:27)
	at org.aksw.sparqlify.config.v0_2.bridge.SchemaProviderImpl.createSchemaForQueryString(SchemaProviderImpl.java:80)
	... 4 more
Caused by: org.postgresql.util.PSQLException: ERROR: relation "users" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2310)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2023)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:217)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:421)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:318)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:281)
	at com.jolbox.bonecp.StatementHandle.executeQuery(StatementHandle.java:464)
	at org.aksw.sparqlify.config.v0_2.bridge.BasicTableProviderJdbc.getRawTypes(BasicTableProviderJdbc.java:42)
	at org.aksw.sparqlify.config.v0_2.bridge.BasicTableProviderJdbc.getBasicTableInfo(BasicTableProviderJdbc.java:25)
	... 5 more

Any clue?
Thank you
D063520

**Comment by Aklakan** [comment]
The lgd-createdb script requires osmosis installed; the readme lacks this information, the script does not perform the check, and the debian package does not declare the dependency
